#THIS FILE IS FOR TESTING ONLY! DO NOT BIND A IP TO A PORT IN DOCKER UNLESS YOU ARE TESTING
version: '2'
services:
    caddy:
        build: .
        ports:
            -   127.0.0.1:80:80
        volumes:
            -   ./public:/var/www/html
        cap_drop:
            - ALL
